### ISSUE TITLE
stems

### ISSUE THREAD

**Issue by richyxi** [nnyj/python-audio-separator-live#1]
Hi!
I run this awesome code and its actually impressive!
however, i was wondering if it can be adapted to run models that extract other stems like drums and bass.

And if its possible, what approach could be?

thanks in advance!

**Comment by nnyj** [comment]
Hey, apologies for the late reply. It is definitely possible but may require digging into the code a little.

Edit: I have not the slightest clue where to begin. It's been 7 months 😆 and it seems the code upstream has some changes. I might get around to it if I do eventually merge. No timeline though, sorry about that.

**Comment by richyxi** [comment]
no worries bro! thanks for answer!

**Comment by xyzalanix** [comment]
Just replace the default model with one of these onnx: https://github.com/TRvlvr/model_repo/releases/tag/all_public_uvr_models

`kuielab_b_drums` works really well. Hope it's still useful.

python live.py -i 1 -o 8 --model_file_dir ./models/ --model_name kuielab_b_drums.onnx
